### ISSUE TITLE
[BUG] Out of memory errors in queue consumer after couple of hours

### ISSUE THREAD

**Issue by JorritSalverda** [cloudflare/workers-rs#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.18

### What version of `wrangler` are you using?

3.5.0

### Describe the bug

With a worker that consumes queue messages one at a time - see config below - after a while memory errors start happening even before code gets executed.

Relevent wrangler.toml config parts:

```toml
name = "***"
main = "build/worker/shim.mjs"
compatibility_date = "2023-08-01"

workers_dev = false
usage_model = "unbound"
logpush = true

[[queues.consumers]]
  queue = "***"
  max_batch_size = 1
  max_concurrency = 3
  max_retries = 0

[vars]
WORKERS_RS_VERSION = "0.0.18"

[build]
command = "cargo install --quiet --force worker-build --version 0.0.10 && worker-build --release"
```

At first things run fine but after a couple of hours the following error happens for every single message delivered through the queue. Events fire approx every 30 seconds.

```json
{
  "outcome": "exception",
  "scriptName": "***",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "CompileError",
      "message": "memory access out of bounds",
      "timestamp": 1691997931293
    }
  ],
  "logs": [],
  "eventTimestamp": 1691997931293,
  "event": {
    "batchSize": 1,
    "queue": "***"
  },
  "id": 107
}
```

I'm wondering if this even has anything to do with the Rust code itself. The code does the following. Only the log appender runs across multiple events, all other parts are initialized - and discarded - for every single event:

```rust
#[event(start)]
pub fn init() {
    console_log::init_with_level(Level::Debug).expect("Failed initializing console log");
}

// Consume messages from a queue
#[event(queue)]
pub async fn main(
    message_batch: MessageBatch<QueueMessageEnvelope>,
    env: Env,
    _ctx: Context,
) -> worker::Result<()> {
    ...

    Ok(())
}

```

Is there any way to print memory usage in code? I could at least track memory usage before things start failing and see if it slowly increases.
