### ISSUE TITLE
[feature] how to avoid wrangler server down when [build].command run error

### ISSUE THREAD

**Issue by ganluo960214** [cloudflare/workers-rs#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.4.1

### What version of `wrangler` are you using?

3.80.5

### Describe the bug

when writing code sometimes will save can't complied code. then wrangler will run `[build].command` config in `wrangler.toml`. i try to wapper it in cargo watch but it could't show `[wrangler:inf] Ready on http://127.0.0.1:8787`.

```toml
[build]
#command = "cargo install -q worker-build && cargo watch -s \"worker-build --dev\""
command = "cargo install -q worker-build && worker-build --dev"
```
