### ISSUE TITLE
[Feature] <title>

### ISSUE THREAD

**Issue by rkedward** [cloudflare/workers-rs#732]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Can we have support for email workers?  I searched the docs and web can't find any examples how process emails using email workers in Rust.

**Comment by devnull03** [comment]
There is a PR #715 that is implementing this feature, it just hasn't been approved yet. I also wanted to use email worker, so I have the fork added as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) ([changed to the feature branch](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule)) in my repo and changed the Cargo.toml accordingly to use the local crate. 

```toml
[dependencies]
worker = { path = "../workers-rs/worker", features=['http'] }
worker-macros = { path = "../workers-rs/worker-macros", features=['http'] }
```
(Your folder paths will be different probably)
